export class diagnostico {

  constructor(

    public firma: String,
    public nombreEmpresa: String,
    public autoriza: String,
    public antiguedad: String,
    public typeOrganizacion: String,
    public dSocio1: String,
    public dSocio2: String,
    public dSocio3: String,
    public eTipoSociedad: String,
    public fPoliticas: String,
    public gPoliticasSi: String,
    public hSeguroEmpresarial: String,
    public iOrganigrama: String,
    // etapa2
    public aVision: String,
    public bMision: String,
    public cCreencias: String,
    public dValores: String,
    public ePrincipios: String,
    public fTipoDeLiderazgo: String,
    public gEquipoDirectivo: String,
    public hLogros: String,
    public iProyectos: String,
    public fortalezasDirectivo: String,
    public debilidadesDirectivo: String,
    // Etapa3
    public aProgramaCrecimiento: String,
    public bRasgos: String,
    public cCapacitacion: String,
    public dPlanDeVida: String,
    public eInduccion: String,
    public ePorque: String,
    public fMujeres: Number,
    public gHombres: Number,
    public hReactivo: String,
    public fortalezasGeneral: String,
    public debilidadesGeneral: String,
    // Etapa4
    public aObjetivos: String,
    public bFodaTime: String,
    public bFodaPlanea: String,
    public bFodaOportunidades: String,
    public bFodaAmenazas: String,
    public bFodaEstrategia: String,
    public cControlGestion: String,
    public cEsquema: String,
    // Etapa5
    public aTipoEmpresa: String,
    public bPlantas: Number,
    public bTamaño: Number,
    public cLineasPro: String,
    public dNumerosEmpleados: Number,
    public eCapacidadProductiva: String,
    public fModificacionsPlanta: String,
    public gPorqueModificacion: String,
    public hTecnologia: String,
    public iManteyRep: String,
    public jMateriaPrima: String,
    public kHerramientas: String,
    public lSuministroG: String,
    public mFortalezas: String,
    public mDebilidades: String,
    // Etapa6
    public aMercadotecnica: String,
    public bParticipacion: String,
    public cLineasProd: String,
    public dProdProm: String,
    public eRegMar: String,
    public fProm: String,
    public gCadenaDis: String,
    public hEscala: String,
    public iTipoPublic: String,
    public jFuerzaVen: String,
    public kTipoDeCapac: String,
    public lFortalezas: String,
    public lDebilidades: String,
    // etapa7
    public aPatentes: String,
    public bInvProyect: String,
    public cInvUniv: String,
    public dProdCal: String,
    public eProveeduria: String,
    //Etapa8
    public aPrincObj: String,
    // b pendiente
    public cPersonaFina: String,
    public dPresupuesto: String,
    public eEndeudamiento: String,
    public fVentasCredito: String,
    public gApalancamiento: String,
    public hMinImpA: String,
    public hMinImpB: String,
    public hMinImpC: String,
    // Etapa9
    public aCadenaValor: String,
    public aCadenaValorPor: String,
    // b pendiente
    public cVentajaComp: String,
    public dConsiAli: String,
    public eConoPort: String,
    public fCertificaciones: String,
    public gCertiType: String,
    public gCertiTypeCuales: String,
    public hConoceA: String,
    public hConoceB: String,
    public hConoceC: String,
    public hConoceD: String,
    public hConoce5: String,
    public hConoce6: String,
    public hConoce7: String,
    public hConoce8: String,
    public hConoce9: String,
    public hConoce10: String,
    public iComentariosAdi: String,
    public file1: String,
    public file2: String

  ) { }
}
