export interface diagInterface {

  autoriza: String,
  firma: String,
  nombreEmpresa: String;
  antiguedad: String;
  typeOrganizacion: String;
  dSocio1: String;
  dSocio2: String;
  dSocio3: String;
  eTipoSociedad: String;
  fPoliticas: String;
  gPoliticasSi: String;
  hSeguroEmpresarial: String;
  iOrganigrama: String;
  // etapa2
  aVision: String;
  bMision: String;
  cCreencias: String;
  dValores: String;
  ePrincipios: String;
  fTipoDeLiderazgo: String;
  gEquipoDirectivo: String;
  hLogros: String;
  iProyectos: String;
  fortalezasDirectivo: String;
  debilidadesDirectivo: String;
  // Etapa3
  aProgramaCrecimiento: String;
  bRasgos: String;
  cCapacitacion: String;
  dPlanDeVida: String;
  eInduccion: String;
  ePorque: String;
  fMujeres: Number;
  gHombres: Number;
  hReactivo: String;
  fortalezasGeneral: String;
  debilidadesGeneral: String;
  // Etapa4
  aObjetivos: String;
  bFodaTime: String;
  bFodaPlanea: String;
  bFodaOportunidades: String;
  bFodaAmenazas: String;
  bFodaEstrategia: String;
  cControlGestion: String;
  cEsquema: String;
  // Etapa5
  aTipoEmpresa: String;
  bPlantas: Number;
  bTamaño: Number;
  cLineasPro: String;
  dNumerosEmpleados: Number;
  eCapacidadProductiva: String;
  fModificacionsPlanta: String;
  gPorqueModificacion: String;
  hTecnologia: String;
  iManteyRep: String;
  jMateriaPrima: String;
  kHerramientas: String;
  lSuministroG: String;
  mFortalezas: String;
  mDebilidades: String;
  // Etapa6
  aMercadotecnica: String;
  bParticipacion: String;
  cLineasProd: String;
  dProdProm: String;
  eRegMar: String;
  fProm: String;
  gCadenaDis: String;
  hEscala: String;
  iTipoPublic: String;
  jFuerzaVen: String;
  kTipoDeCapac: String;
  lFortalezas: String;
  lDebilidades: String;
  // etapa7
  aPatentes: String;
  bInvProyect: String;
  cInvUniv: String;
  dProdCal: String;
  eProveeduria: String;
  //Etapa8
  aPrincObj: String;
  // b pendiente
  cPersonaFina: String;
  dPresupuesto: String;
  eEndeudamiento: String;
  fVentasCredito: String;
  gApalancamiento: String;
  hMinImpA: String;
  hMinImpB: String;
  hMinImpC: String;
  // Etapa9
  aCadenaValor: String;
  aCadenaValorPor: String;
  // b pendiente
  cVentajaComp: String;
  dConsiAli: String;
  eConoPort: String;
  fCertificaciones: String;
  gCertiType: String;
  gCertiTypeCuales: String;
  hConoceA: String;
  hConoceB: String;
  hConoceC: String;
  hConoceD: String;
  hConoce5: String;
  hConoce6: String;
  hConoce7: String;
  hConoce8: String;
  hConoce9: String;
  hConoce10: String;
  iComentariosAdi: String;
  file1: String;
  file2: String;

}
